name: Test Android

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'app/**'
      - 'gradle/**'
      - '*.gradle*'
      - '.github/workflows/test_android.yml'
  push:
    branches:
      - feature/*

jobs:
  test_android:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt (Static Analysis)
        run: ./gradlew detekt

      - name: Run Unit Tests with Coverage
        run: ./gradlew testDebugUnitTest createDebugUnitTestCoverageReport --continue

      - name: Run Connected Tests with Coverage
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          script: |
            ./gradlew connectedDebugAndroidTest --continue
            ./gradlew createDebugCoverageReport --continue || true

      - name: Merge Coverage Reports
        if: always()
        run: |
          # Ensure coverage reports exist
          ls -la app/build/reports/jacoco/ || echo "No jacoco reports"
          ls -la app/build/reports/coverage/ || echo "No coverage reports"

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload Instrumented Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instrumented-test-results
          path: app/build/reports/androidTests/connected/

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-coverage
          path: |
            app/build/reports/jacoco/
            app/build/reports/coverage/

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detekt-report
          path: app/build/reports/detekt/

      - name: Comment Coverage on PR
        uses: madrapps/jacoco-report@v1.6.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            ${{ github.workspace }}/app/build/reports/jacoco/createDebugUnitTestCoverageReport/createDebugUnitTestCoverageReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
